version: 1.0.{build}
image: Visual Studio 2015
init:
- git config --global core.autocrlf true
install:
- ps: Install-Product node 6
- npm install -g npm@6
branches:
  only:
  - master
environment:
  JAVA6_HOME: C:/Program Files/Java/jdk1.6.0/jre
build_script:
- npm install
- npm run tslint
test_script:
- npm test
cache:
- node_modules -> **\package.json
- C:\Users\appveyor\.m2 -> **\pom.xml
